language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml